###################### Data Split configuration #####################
subjects:
  train: 
    - 'STLE_0125'
    - 'STLE_0094' 
    - 'STL_0053'
    - 'STLE_0099'
    - 'STLE_0250'
    - 'STLW_0341'
    - 'STLE_0140'
  eval:
    - 'STLE_0223'
  test:
    - 'SF_0034'
    - 'STLE_0372'

###################### Data Preprocessing parameters #####################
preprocessing:
  target_rate: 30
  window_len: 8.0
  stride_ratio: 1.0
  signal_cols:
    - 'bp'
    - 'breath_upper' 
    - 'ppg_fing'

